### ISSUE TITLE
Typo correction in README.md: 'discussion' to 'discussions'

### ISSUE THREAD

**Issue by add-ict** [prosyslab-classroom/cs424-program-reasoning#402]
## Description
There is a typo in the README.md file that needs to be corrected.

**Location:** Line 73

**Current text:**
```
...for GitHub Classroom will be posted in the [Discussion board](../../discussion).
```

**Corrected text:**
```
...for GitHub Classroom will be posted in the [Discussion board](../../discussions).
```

**Change required:** Update 'discussion' to 'discussion**s**' in the URL.

## Additional Information
This change ensures the correct linking to the Discussions section of the repository.

---
Please review this change to improve the accuracy of the documentation. Thank you!

**Comment by KihongHeo** [comment]
Thanks!
